name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with Allure
        run: |
          mkdir -p reports/allure
          pytest --alluredir=reports/allure
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/allure

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre wget unzip
          wget -qO allure.zip https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.zip
          unzip -q allure.zip
          sudo mv allure-2.29.0 /opt/allure
          sudo ln -sf /opt/allure/bin/allure /usr/local/bin/allure
      - name: Generate Allure HTML report
        run: |
          allure generate reports/allure --clean -o reports/allure-html
      - name: Upload Allure HTML report
        uses: actions/upload-artifact@v4
        with:
          name: allure-html
          path: reports/allure-html
